# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    parallelism: 1  # run only 1 instance
    docker:
      - image: circleci/elixir:1.6.4
    working_directory: ~/repo/simplest_nn
    environment:
      MIX_ENV: test
    steps:
      - checkout:
          path: ~/repo
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get --only test
      - run: mix test
      - run: mix format --check-formatted
      - run: mix compile